#' Converge_figs() pulls convergence figures for each parameter
#' @param distribution One of `'Normal'`, `'Skewed'`, `'Lognormal'`, `'Gamma'`, or `'Beta'`.
#' @param jags_model_run The output list returned from [run_likelihood()],
#' which includes the jags model `run_results`, likelihood distribution type,
#' `data`, `xvals`, and `future_tests` that were used as inputs to [run_likelihood()]
#' @description
#' The convergence summary plots generated by [runjags::run.jags()] for the defining
#' parameters of the selected distribution
#' @returns A list of histograms and MCMC chain plots per parameter
#' @export
#' @import patchwork
converge_figs=function(distribution,jags_model_run){
  if (distribution=="Normal"){
    par_list=c('emission_mean','emission_sd')
  } else if (distribution=="Lognormal"){
    par_list=c('u_ln','sd_ln')
  } else if (distribution=="Skewed"){
    par_list=c('omega','xi','alpha')
  } else if (distribution=="Gamma"){
    par_list=c('rate_em','shape_em')
  } else if (distribution=="Beta"){
    par_list=c('alpha_em','beta_em')
  }
  fig_list=list()
  for (i in 1:length(par_list))
    local({
      i=i
      step3=coda::as.mcmc.list(jags_model_run$run_results, vars=par_list[i])
      step4=runjags::combine.mcmc(step3)
      p1=ggplot2::ggplot()+
        ggplot2::geom_line(ggplot2::aes(color='a',x=1:10000,
                                        y=as.vector(step3[[1]])),
                            linewidth = 0.5,linetype = 1)+
        ggplot2::geom_line(ggplot2::aes(color='b',x=1:10000,
                                        y=as.vector(step3[[2]])),
                  linewidth = 0.5,linetype = 2)+
        ggplot2::geom_line(ggplot2::aes(color='c',x=1:10000,
                                        y=as.vector(step3[[3]])),
                  linewidth = 0.5,linetype = 3)+
        mcmc_theme()+ggplot2::xlab('Iterations')+ggplot2::ylab(par_list[i])
      p2=ggplot2::ggplot()+ggplot2::geom_histogram(ggplot2::aes(step4),
                                          color='black',fill='grey')+
        ggplot2::xlab(par_list[i])+mcmc_theme()
      p12=p1+p2+patchwork::plot_layout(ncol=2)+
        patchwork::plot_annotation(title=distribution) &
        ggplot2::theme(plot.title = ggplot2::element_text(size=20,hjust=0.5))
    fig_list[[i]]<<-p12
    })
  return(fig_list)
}
