#' Converge_figsGroup() pulls convergence figures for each parameter with a hierarchical group structure
#' @param distribution Any of `'Normal'`, `'Gamma'`, `'Skewed'`, `'Lognormal'`,
#' or `'Beta'`. If using a custom model script, set as `'Custom'`.
#' @param jags_model_run The output list returned from [run_likelihoodGroup()],
#' which includes the jags model `run_results`, likelihood distribution type,
#' `data`, `xvals`, and `future_tests` that were used as inputs to [run_likelihoodGroup()].
#' @param custom_params List of parameters to check for convergence if using a
#' custom model, e.g. `c('parameter1', 'parameter2')`. These must be ordered
#' such that all population-level parameters are first followed by group-level parameters.
#' @description
#' The convergence summary plots generated by [runjags::run.jags()] for the defining
#' parameters of the selected distribution. Rather than independent runs defining the population
#' distribution, hierarchical dependency within groups is allowed with the
#' group-level distribution parameters drawn from the overall population distribution.
#' @returns A list of histograms and MCMC chain plots per parameter
#' @export
#' @import patchwork
converge_figsGroup = function(distribution, jags_model_run,
                              custom_params = NULL){
  if (distribution == "Normal"){
    par_list = c('pop_mu_mu', 'pop_sd_mu', 'pop_mu_sd', 'pop_sd_sd',
                 'group_sd', 'group_mu')
  } else if (distribution == "Lognormal"){
    par_list = c('pop_mu_mu', 'pop_sd_mu', 'pop_mu_sd', 'pop_sd_sd',
                 'group_sd', 'group_mu')
  } else if (distribution == "Skewed"){
    par_list = c('pop_xi_mu', 'pop_omega_mu',
                 'pop_alpha_mu',  'pop_xi_sd', 'pop_omega_sd',
                 'pop_alpha_sd', 'omega', 'xi', 'alpha')
  } else if (distribution == "Gamma"){
    par_list = c('pop_rate_mu', 'pop_shape_mu', 'pop_rate_sd', 'pop_shape_sd',
                 'group_rate', 'group_shape')
  } else if (distribution == "Beta"){
    par_list = c('pop_alpha_mu', 'pop_beta_mu', 'pop_alpha_sd', 'pop_beta_sd',
                 'group_alpha', 'group_beta')
  } else if (distribution == "Custom"){
    par_list = custom_params
  }
  n_groups = length(unique(jags_model_run$data$group))
  n_pop_params = length(par_list) / 3 * 2
  params = c(par_list[1:n_pop_params],
             sprintf(paste0(par_list[n_pop_params+1], '[%s]'),
                     seq(1:n_groups)),
             sprintf(paste0(par_list[n_pop_params+2], '[%s]'),
                     seq(1:n_groups)))
  group_levels = levels(jags_model_run$data$group)
  param_name = params
  for (i in 1:n_groups){
    param_name = stringr::str_replace(param_name, paste0('\\[', i, '\\]'),
                                          paste0('_', group_levels[i]))
  }
  fig_list = list()
  for (i in 1:length(params))
    local({
      i = i
      step3 = coda::as.mcmc.list(jags_model_run$run_results,
                                 vars = params[i])
      step4 = runjags::combine.mcmc(step3)
      var_name = param_name[i]
      p1 = ggplot2::ggplot()+
        ggplot2::geom_line(ggplot2::aes(color = 'a', x = 1:10000,
                                        y = as.vector(step3[[1]])),
                           linewidth = 0.5,linetype = 1)+
        ggplot2::geom_line(ggplot2::aes(color = 'b',x = 1:10000,
                                        y = as.vector(step3[[2]])),
                           linewidth = 0.5,linetype = 2)+
        ggplot2::geom_line(ggplot2::aes(color = 'c',x = 1:10000,
                                        y = as.vector(step3[[3]])),
                           linewidth = 0.5,linetype = 3)+
        mcmc_theme() + ggplot2::xlab('Iterations') +
        ggplot2::ylab(var_name)
      p2 = ggplot2::ggplot() +
        ggplot2::geom_histogram(ggplot2::aes(step4),
                                color = 'black', fill = 'grey')+
        ggplot2::xlab(var_name) + mcmc_theme()
      p12 = p1 + p2 + patchwork::plot_layout(ncol = 2) +
        patchwork::plot_annotation(title = distribution) &
        ggplot2::theme(plot.title =
                         ggplot2::element_text(size = 20, hjust = 0.5))
      fig_list[[i]]<<-p12
    })
  return(fig_list)
}
